authors:
  alitiq:
    name: alitiq GmbH        # Author name
    description: alitiq Forecasting Company # Author description
    avatar: alitiq_logo_white.png         # Author avatar
    url: https://alitiq.com/            # Author website URL