authors:
  alitiq:
    name: alitiq Forecasting        # Author name
    description: Experts in Weather & AI # Author description
    avatar: assets/cropped-220818_Favicon_alitiq-32x32.jpg         # Author avatar
    url: https://www.alitiq.com/            # Author website URL